simulation:
        cars: 2
        mobility:
                distance:
                        x: 600
                        y: 600       
                repetitions: 3
        communication:
                repetitions: 3
        speed:
                index: 
                        - 0
                value:
                        - 13.88889 # 50 km/h
        model:
                name: 
                        - "RESNET10"
                size: 500
        data:
                name:  "SIGN"
                alpha: 5.0
                shape: 32,32,3
                n_classes: 10

        federated_learning:
                server:
                        log_path: "logs/server/flwr/"
                        model_path: "models/server/flwr/"
                        time_path: "results/server/flwr"
                        strategy: "fedavg"
                        rounds: 10
                        ip: "0.0.0.0"
                        port: "8081"
                        n_clients_selected: 5
                client:
                        local_epochs: 5
        base_station:
                range: 1200
                positions: "configs/base_stations.csv"

